services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: top-songs-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      APP_ENV: dev
    # Add depends_on for Kafka, Postgres, etc. as you add those services

# To extend: add kafka, minio, postgres, etc. as needed 