[project]
name = "top-songs-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka>=2.10.0",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
    "typer>=0.15.3",
]
